
language: swift

matrix:
    include:
        - os: osx
          osx_image: xcode9
          script:
            - swift package tools-version --set 4.0.0
            - swift package update
            - swift test
